## English Premier League (EPL) Match Data 2000-2025

In [7]:
# importing the libraries 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import ElasticNetCV,RidgeCV,LassoCV

In [26]:
df=pd.read_csv(r"D:\Downloads\archive\epl_final.csv") # loading the dataset using csv  
df=pd.DataFrame(df) # converting the csv file in dataframe for our analysis 
print(df)

       Season   MatchDate        HomeTeam       AwayTeam  FullTimeHomeGoals  \
0     2000/01  2000-08-19        Charlton       Man City                  4
1     2000/01  2000-08-19         Chelsea       West Ham                  4
2     2000/01  2000-08-19        Coventry  Middlesbrough                  1
3     2000/01  2000-08-19           Derby    Southampton                  2
4     2000/01  2000-08-19           Leeds        Everton                  2
...       ...         ...             ...            ...                ...
9375  2024/25  2025-05-04       Brentford     Man United                  4
9376  2024/25  2025-05-04        Brighton      Newcastle                  1
9377  2024/25  2025-05-04        West Ham      Tottenham                  1
9378  2024/25  2025-05-04         Chelsea      Liverpool                  3
9379  2024/25  2025-05-05  Crystal Palace  Nott'm Forest                  1

      FullTimeAwayGoals FullTimeResult  HalfTimeHomeGoals  HalfTimeAwayGoals  \
0                     0              H                  2                  0
1                     2              H                  1                  0
2                     3              A                  1                  1
3                     2              D                  1                  2
4                     0              H                  2                  0
...                 ...            ...                ...                ...
9375                  3              H                  2                  1
9376                  1              D                  1                  0
9377                  1              D                  1                  1
9378                  1              H                  1                  0
9379                  1              D                  0                  0

     HalfTimeResult  ...  HomeShotsOnTarget  AwayShotsOnTarget  HomeCorners  \
0                 H  ...                 14                  4            6
1                 H  ...                 10                  5            7
2                 D  ...                  3                  9            8
3                 A  ...                  4                  6            5
4                 H  ...                  8                  6            6
...             ...  ...                ...                ...          ...
9375              H  ...                  6                  5            7
9376              H  ...                  2                  5            1
9377              D  ...                  2                  2            1
9378              H  ...                  7                  2            3
9379              D  ...                  3                  4            7

      AwayCorners  HomeFouls  AwayFouls  HomeYellowCards  AwayYellowCards  \
0               6         13         12                1                2
1               7         19         14                1                2
2               4         15         21                5                3
3               8         11         13                1                1
4               4         21         20                1                3
...           ...        ...        ...              ...              ...
9375            4          8         10                0                2
9376            4         15         10                2                1
9377            3         18         15                2                2
9378            6         10         11                2                2
9379            4          9         15                3                8

      HomeRedCards  AwayRedCards
0                0             0
1                0             0
2                1             0
3                0             0
4                0             0
...            ...           ...
9375             0             0
9376             0             0
9377             0             0
9378             0             0
9379             0             0

[9380 rows x 22 columns]

In [12]:
df.head() # for displaying the first 5  rows of data in our csv file

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0

In [14]:
df.tail() # seeing the last five rows in our data set

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
9375,2024/25,2025-05-04,Brentford,Man United,4,3,H,2,1,H,...,6,5,7,4,8,10,0,2,0,0
9376,2024/25,2025-05-04,Brighton,Newcastle,1,1,D,1,0,H,...,2,5,1,4,15,10,2,1,0,0
9377,2024/25,2025-05-04,West Ham,Tottenham,1,1,D,1,1,D,...,2,2,1,3,18,15,2,2,0,0
9378,2024/25,2025-05-04,Chelsea,Liverpool,3,1,H,1,0,H,...,7,2,3,6,10,11,2,2,0,0
9379,2024/25,2025-05-05,Crystal Palace,Nott'm Forest,1,1,D,0,0,D,...,3,4,7,4,9,15,3,8,0,0

In [16]:
df.describe() # describing our dataset it give the mean and count and etc etc

,FullTimeHomeGoals,FullTimeAwayGoals,HalfTimeHomeGoals,HalfTimeAwayGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
count,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000
mean,1.535394,1.182623,0.688273,0.518763,13.617484,10.810661,5.973134,4.693710,6.040299,4.774733,11.276333,11.765672,1.468124,1.792431,0.062473,0.085288
std,1.305432,1.157414,0.835079,0.735357,5.356424,4.696501,3.267954,2.750045,3.110619,2.749541,3.750250,3.924179,1.217190,1.288481,0.253221,0.290183
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,7.000000,4.000000,3.000000,4.000000,3.000000,9.000000,9.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,10.000000,6.000000,4.000000,6.000000,4.000000,11.000000,12.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,14.000000,8.000000,6.000000,8.000000,6.000000,14.000000,14.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,24.000000,20.000000,20.000000,19.000000,33.000000,29.000000,7.000000,9.000000,3.000000,2.000000

In [18]:
df.info() # checking the information of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             9380 non-null   object
 1   MatchDate          9380 non-null   object
 2   HomeTeam           9380 non-null   object
 3   AwayTeam           9380 non-null   object
 4   FullTimeHomeGoals  9380 non-null   int64
 5   FullTimeAwayGoals  9380 non-null   int64
 6   FullTimeResult     9380 non-null   object
 7   HalfTimeHomeGoals  9380 non-null   int64
 8   HalfTimeAwayGoals  9380 non-null   int64
 9   HalfTimeResult     9380 non-null   object
 10  HomeShots          9380 non-null   int64
 11  AwayShots          9380 non-null   int64
 12  HomeShotsOnTarget  9380 non-null   int64
 13  AwayShotsOnTarget  9380 non-null   int64
 14  HomeCorners        9380 non-null   int64
 15  AwayCorners        9380 non-null   int64
 16  HomeFouls          9380 non-null   int64
 17  AwayFouls          9380 non-null   int64
 18  HomeYellowCards    9380 non-null   int64
 19  AwayYellowCards    9380 non-null   int64
 20  HomeRedCards       9380 non-null   int64
 21  AwayRedCards       9380 non-null   int64
dtypes: int64(16), object(6)
memory usage: 1.6+ MB

In [21]:
df.dtypes ## checking the datatype for each columns

Season               object
MatchDate            object
HomeTeam             object
AwayTeam             object
FullTimeHomeGoals     int64
FullTimeAwayGoals     int64
FullTimeResult       object
HalfTimeHomeGoals     int64
HalfTimeAwayGoals     int64
HalfTimeResult       object
HomeShots             int64
AwayShots             int64
HomeShotsOnTarget     int64
AwayShotsOnTarget     int64
HomeCorners           int64
AwayCorners           int64
HomeFouls             int64
AwayFouls             int64
HomeYellowCards       int64
AwayYellowCards       int64
HomeRedCards          int64
AwayRedCards          int64
dtype: object

In [24]:
df.shape # checking the shape of the dataset it has 9380 rows and 22 columns

(9380, 22)

In [29]:
df.index # checking the index range

RangeIndex(start=0, stop=9380, step=1)

In [31]:
df.columns # important for analysis and checking the relationships

Index(['Season', 'MatchDate', 'HomeTeam', 'AwayTeam', 'FullTimeHomeGoals',
       'FullTimeAwayGoals', 'FullTimeResult', 'HalfTimeHomeGoals',
       'HalfTimeAwayGoals', 'HalfTimeResult', 'HomeShots', 'AwayShots',
       'HomeShotsOnTarget', 'AwayShotsOnTarget', 'HomeCorners', 'AwayCorners',
       'HomeFouls', 'AwayFouls', 'HomeYellowCards', 'AwayYellowCards',
       'HomeRedCards', 'AwayRedCards'],
      dtype='object')

# we want saparate the categrical data numerical data

In [34]:
numerical_columns=[column for column in df.columns if df[column].dtype!='O']
# its divides the numerical columns from our dataset easy to understand

In [33]:
numerical_columns

['FullTimeHomeGoals',
 'FullTimeAwayGoals',
 'HalfTimeHomeGoals',
 'HalfTimeAwayGoals',
 'HomeShots',
 'AwayShots',
 'HomeShotsOnTarget',
 'AwayShotsOnTarget',
 'HomeCorners',
 'AwayCorners',
 'HomeFouls',
 'AwayFouls',
 'HomeYellowCards',
 'AwayYellowCards',
 'HomeRedCards',
 'AwayRedCards']

In [35]:
Categorical_columns=[column for column in df.columns if df[column].dtype == "O" ]

In [36]:
Categorical_columns

['Season',
 'MatchDate',
 'HomeTeam',
 'AwayTeam',
 'FullTimeResult',
 'HalfTimeResult']

In [40]:
df["HomeTeam"]

0             Charlton
1              Chelsea
2             Coventry
3                Derby
4                Leeds
             ...
9375         Brentford
9376          Brighton
9377          West Ham
9378           Chelsea
9379    Crystal Palace
Name: HomeTeam, Length: 9380, dtype: object

# Data preprocessing

In [41]:
# checking for null values and duplicates

In [46]:
print(df.isnull()) # checking for any null values 
print(df.isna()) # checking for any na values 
print(df.notnull()) # checking for not null values 
print(df.notna()) # checking for not na values

      Season  MatchDate  HomeTeam  AwayTeam  FullTimeHomeGoals  \
0      False      False     False     False              False
1      False      False     False     False              False
2      False      False     False     False              False
3      False      False     False     False              False
4      False      False     False     False              False
...      ...        ...       ...       ...                ...
9375   False      False     False     False              False
9376   False      False     False     False              False
9377   False      False     False     False              False
9378   False      False     False     False              False
9379   False      False     False     False              False

      FullTimeAwayGoals  FullTimeResult  HalfTimeHomeGoals  HalfTimeAwayGoals  \
0                 False           False              False              False
1                 False           False              False              False
2                 False           False              False              False
3                 False           False              False              False
4                 False           False              False              False
...                 ...             ...                ...                ...
9375              False           False              False              False
9376              False           False              False              False
9377              False           False              False              False
9378              False           False              False              False
9379              False           False              False              False

      HalfTimeResult  ...  HomeShotsOnTarget  AwayShotsOnTarget  HomeCorners  \
0              False  ...              False              False        False
1              False  ...              False              False        False
2              False  ...              False              False        False
3              False  ...              False              False        False
4              False  ...              False              False        False
...              ...  ...                ...                ...          ...
9375           False  ...              False              False        False
9376           False  ...              False              False        False
9377           False  ...              False              False        False
9378           False  ...              False              False        False
9379           False  ...              False              False        False

      AwayCorners  HomeFouls  AwayFouls  HomeYellowCards  AwayYellowCards  \
0           False      False      False            False            False
1           False      False      False            False            False
2           False      False      False            False            False
3           False      False      False            False            False
4           False      False      False            False            False
...           ...        ...        ...              ...              ...
9375        False      False      False            False            False
9376        False      False      False            False            False
9377        False      False      False            False            False
9378        False      False      False            False            False
9379        False      False      False            False            False

      HomeRedCards  AwayRedCards
0            False         False
1            False         False
2            False         False
3            False         False
4            False         False
...            ...           ...
9375         False         False
9376         False         False
9377         False         False
9378         False         False
9379         False         False

[9380 rows x 22 columns]
      Season  MatchDate  HomeTeam  AwayTeam  FullTimeHomeGoals  \
0      False      False     False     False              False
1      False      False     False     False              False
2      False      False     False     False              False
3      False      False     False     False              False
4      False      False     False     False              False
...      ...        ...       ...       ...                ...
9375   False      False     False     False              False
9376   False      False     False     False              False
9377   False      False     False     False              False
9378   False      False     False     False              False
9379   False      False     False     False              False

      FullTimeAwayGoals  FullTimeResult  HalfTimeHomeGoals  HalfTimeAwayGoals  \
0                 False           False              False              False
1                 False           False              False              False
2                 False           False              False              False
3                 False           False              False              False
4                 False           False              False              False
...                 ...             ...                ...                ...
9375              False           False              False              False
9376              False           False              False              False
9377              False           False              False              False
9378              False           False              False              False
9379              False           False              False              False

      HalfTimeResult  ...  HomeShotsOnTarget  AwayShotsOnTarget  HomeCorners  \
0              False  ...              False              False        False
1              False  ...              False              False        False
2              False  ...              False              False        False
3              False  ...              False              False        False
4              False  ...              False              False        False
...              ...  ...                ...                ...          ...
9375           False  ...              False              False        False
9376           False  ...              False              False        False
9377           False  ...              False              False        False
9378           False  ...              False              False        False
9379           False  ...              False              False        False

      AwayCorners  HomeFouls  AwayFouls  HomeYellowCards  AwayYellowCards  \
0           False      False      False            False            False
1           False      False      False            False            False
2           False      False      False            False            False
3           False      False      False            False            False
4           False      False      False            False            False
...           ...        ...        ...              ...              ...
9375        False      False      False            False            False
9376        False      False      False            False            False
9377        False      False      False            False            False
9378        False      False      False            False            False
9379        False      False      False            False            False

      HomeRedCards  AwayRedCards
0            False         False
1            False         False
2            False         False
3            False         False
4            False         False
...            ...           ...
9375         False         False
9376         False         False
9377         False         False
9378         False         False
9379         False         False

[9380 rows x 22 columns]
      Season  MatchDate  HomeTeam  AwayTeam  FullTimeHomeGoals  \
0       True       True      True      True               True
1       True       True      True      True               True
2       True       True      True      True               True
3       True       True      True      True               True
4       True       True      True      True               True
...      ...        ...       ...       ...                ...
9375    True       True      True      True               True
9376    True       True      True      True               True
9377    True       True      True      True               True
9378    True       True      True      True               True
9379    True       True      True      True               True

      FullTimeAwayGoals  FullTimeResult  HalfTimeHomeGoals  HalfTimeAwayGoals  \
0                  True            True               True               True
1                  True            True               True               True
2                  True            True               True               True
3                  True            True               True               True
4                  True            True               True               True
...                 ...             ...                ...                ...
9375               True            True               True               True
9376               True            True               True               True
9377               True            True               True               True
9378               True            True               True               True
9379               True            True               True               True

      HalfTimeResult  ...  HomeShotsOnTarget  AwayShotsOnTarget  HomeCorners  \
0               True  ...               True               True         True
1               True  ...               True               True         True
2               True  ...               True               True         True
3               True  ...               True               True         True
4               True  ...               True               True         True
...              ...  ...                ...                ...          ...
9375            True  ...               True               True         True
9376            True  ...               True               True         True
9377            True  ...               True               True         True
9378            True  ...               True               True         True
9379            True  ...               True               True         True

      AwayCorners  HomeFouls  AwayFouls  HomeYellowCards  AwayYellowCards  \
0            True       True       True             True             True
1            True       True       True             True             True
2            True       True       True             True             True
3            True       True       True             True             True
4            True       True       True             True             True
...           ...        ...        ...              ...              ...
9375         True       True       True             True             True
9376         True       True       True             True             True
9377         True       True       True             True             True
9378         True       True       True             True             True
9379         True       True       True             True             True

      HomeRedCards  AwayRedCards
0             True          True
1             True          True
2             True          True
3             True          True
4             True          True
...            ...           ...
9375          True          True
9376          True          True
9377          True          True
9378          True          True
9379          True          True

[9380 rows x 22 columns]
      Season  MatchDate  HomeTeam  AwayTeam  FullTimeHomeGoals  \
0       True       True      True      True               True
1       True       True      True      True               True
2       True       True      True      True               True
3       True       True      True      True               True
4       True       True      True      True               True
...      ...        ...       ...       ...                ...
9375    True       True      True      True               True
9376    True       True      True      True               True
9377    True       True      True      True               True
9378    True       True      True      True               True
9379    True       True      True      True               True

      FullTimeAwayGoals  FullTimeResult  HalfTimeHomeGoals  HalfTimeAwayGoals  \
0                  True            True               True               True
1                  True            True               True               True
2                  True            True               True               True
3                  True            True               True               True
4                  True            True               True               True
...                 ...             ...                ...                ...
9375               True            True               True               True
9376               True            True               True               True
9377               True            True               True               True
9378               True            True               True               True
9379               True            True               True               True

      HalfTimeResult  ...  HomeShotsOnTarget  AwayShotsOnTarget  HomeCorners  \
0               True  ...               True               True         True
1               True  ...               True               True         True
2               True  ...               True               True         True
3               True  ...               True               True         True
4               True  ...               True               True         True
...              ...  ...                ...                ...          ...
9375            True  ...               True               True         True
9376            True  ...               True               True         True
9377            True  ...               True               True         True
9378            True  ...               True               True         True
9379            True  ...               True               True         True

      AwayCorners  HomeFouls  AwayFouls  HomeYellowCards  AwayYellowCards  \
0            True       True       True             True             True
1            True       True       True             True             True
2            True       True       True             True             True
3            True       True       True             True             True
4            True       True       True             True             True
...           ...        ...        ...              ...              ...
9375         True       True       True             True             True
9376         True       True       True             True             True
9377         True       True       True             True             True
9378         True       True       True             True             True
9379         True       True       True             True             True

      HomeRedCards  AwayRedCards
0             True          True
1             True          True
2             True          True
3             True          True
4             True          True
...            ...           ...
9375          True          True
9376          True          True
9377          True          True
9378          True          True
9379          True          True

[9380 rows x 22 columns]

In [52]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0

In [57]:
print(df.dropna().sum()) # we droping the na values for our dataset 
#print(df.fillna.mean("FullTimeHomeGoals")) # if in case if their any values we are the filling the na's

Season               2000/012000/012000/012000/012000/012000/012000...
MatchDate            2000-08-192000-08-192000-08-192000-08-192000-0...
HomeTeam             CharltonChelseaCoventryDerbyLeedsLeicesterLive...
AwayTeam             Man CityWest HamMiddlesbroughSouthamptonEverto...
FullTimeHomeGoals                                                14402
FullTimeAwayGoals                                                11093
FullTimeResult       HHADHDHHHHHHDDHHHAAHDDHAAHDDDAHDHDDADHHDDAHHHA...
HalfTimeHomeGoals                                                 6456
HalfTimeAwayGoals                                                 4866
HalfTimeResult       HHDAHDDDHHHHDADHDADADHDAAHAADAHDADHAADHHDADHHH...
HomeShots                                                       127732
AwayShots                                                       101404
HomeShotsOnTarget                                                56028
AwayShotsOnTarget                                                44027
HomeCorners                                                      56658
AwayCorners                                                      44787
HomeFouls                                                       105772
AwayFouls                                                       110362
HomeYellowCards                                                  13771
AwayYellowCards                                                  16813
HomeRedCards                                                       586
AwayRedCards                                                       800
dtype: object

In [58]:
df["FullTimeHomeGoals"] = df["FullTimeHomeGoals"].fillna(
    df["FullTimeHomeGoals"].mean()
)