What are duplicates?
1) Aduplicate entry means the same record appers more than once in ypur dataset

In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [27]:
data={"Id":[101,102,103,102,104],
      "Name":["Rahul","Priya","Amit","Priya","Neha"],
      "Age":[25,28,30,28,26],
      "City":["Delhi","Mumbai","Pune","Mumbai","Delhi"]
}
ddf=pd.DataFrame(data)
print(ddf)

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
3  102  Priya   28  Mumbai
4  104   Neha   26   Delhi

In [7]:
print(df.duplicated()) # a simple command for printing the duplicates 
# if any duplicate is present it shows true either it shows false

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [8]:
duplicates=df[df.duplicated()]
print(duplicates) #  The way to showing only duplicates rows

    Id   Name  Age    City
3  102  Priya   28  Mumbai

In [9]:
df[df.duplicated()] # used to find the occurance of all duplicates

    Id   Name  Age    City
3  102  Priya   28  Mumbai

In [10]:
df[df.duplicated(keep=False)] #  its shows both copies 
# Keep=False "mark Every occurance of a duplicate as tuple"

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [11]:
# checking duplicates based on column 
print(df[df.duplicated("Id",keep=False)])
# this is extremely useful for finding duplicate customer ids employee ids ,product ids
#transaction ids,etc

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [12]:
# checking duplicates using multiple colomns 
print(df[df.duplicated(["Name","Age","Id"],keep=False)])
# we want to check for thr  multiple colomns we need to give the square brakets

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [13]:
# count the number of duplicate rows 
print(df.duplicated().sum())

1

In [14]:
# remove duplicates 
print("duplicates removed as per ur requirement")
data=df.drop_duplicates()
print(data)

duplicates removed as per ur requirement
    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [15]:
# removing duplicates based up on columns
print(df.drop_duplicates(subset=["Name"],keep=False))

    Id   Name  Age   City
0  101  Rahul   25  Delhi
2  103   Amit   30   Pune
4  104   Neha   26  Delhi

# what is correlation?
1) correlation tells us how strongly two numerical variables are related to each other
* correlation generally ranges from -1 to +1 
* +1 perfect positive relationship 
* +0.7 to +1 Strong Postive relation 
* +0.3 to +0.7 Moderate positive relationship
* 0 no linear relationship
* -0.3 to 0 weak negative relationship
* -0.7 to -0.3 Moderate negative relationship
* -1 perfect negative relationship

In [16]:
data1={
    "hourse_studied":[2,3,4,5,6,7,8],
    "Exam_Score":[50,55,60,65,70,75,80]
}
df=pd.DataFrame(data1)
print(df)

   hourse_studied  Exam_Score
0               2          50
1               3          55
2               4          60
3               5          65
4               6          70
5               7          75
6               8          80

In [17]:
# method1 using .corr
correlation=df["hourse_studied"].corr(df["Exam_Score"])
print(correlation) # WE are getting the perfect correlation

1.0

In [18]:
data = {
    "Exercise_Hours": [1, 2, 3, 4, 5],
    "Weight": [80, 77, 74, 71, 68]
} # this perfect negative correlation 
pf = pd.DataFrame(data)
print(pf["Exercise_Hours"].corr(pf["Weight"]))

-1.0

In [19]:
# correlation between multiple columns 
print(df.corr(numeric_only=True))
df.columns

                hourse_studied  Exam_Score
hourse_studied             1.0         1.0
Exam_Score                 1.0         1.0

Index(['hourse_studied', 'Exam_Score'], dtype='object')

In [20]:
# correlation between specific columns 
print(df["hourse_studied"].corr(df["Exam_Score"]))

1.0

In [21]:
# finding the strongest correlation in our dataset 
corr_matrix=df.corr(numeric_only=True)
print(corr_matrix)

                hourse_studied  Exam_Score
hourse_studied             1.0         1.0
Exam_Score                 1.0         1.0

In [22]:
print(df.corr(numeric_only=True)["Exam_Score"].sort_values(ascending=False))
# this shows how strongly every numerical variable is correlated with Exam-score

hourse_studied    1.0
Exam_Score        1.0
Name: Exam_Score, dtype: float64

In [36]:
# can you write the a python function to remove the duplicates from the dataset
import pandas as pd 
def remove_duplicates(df):
    df=ddf.drop_duplicates()
    return df
df=remove_duplicates(df)
print(df)

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [37]:
ddf

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [47]:
ddf.drop_duplicates(inplace=True)
print(ddf)

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [51]:
ddf.drop_duplicates(subset=["Id"],inplace=True)
print(ddf)

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [58]:
df=ddf.drop_duplicates(subset=["Id"],keep="last",inplace=True)
print(df)

None

In [59]:
# write a python function to scale numerical data between 0 and 1
data={
    "Age":[20,25,30,35,40],
    "Salary":[20000,30000,40000,50000,60000]
}
df=pd.DataFrame(data)
print(df)

   Age  Salary
0   20   20000
1   25   30000
2   30   40000
3   35   50000
4   40   60000

In [60]:
from sklearn.preprocessing import MinMaxScaler

In [61]:
scaler=MinMaxScaler()
data=df[["Age","Salary"]]
Scaled_data=scaler.fit_transform(data)
print(Scaled_data)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]

In [82]:
from sklearn.preprocessing import MinMaxScaler
def Scale_data(data):
    scaler=MinMaxScaler()
    Scaled_data=scaler.fit_transform(data)
    return Scaled_data

In [83]:
Scaled_data=Scale_data(df[["Age","Salary"]])
print(Scaled_data)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]

In [87]:
Scaler=MinMaxScaler()
data=df[["Age"]]
Scaled_data=Scaler.fit_transform(data)
print(Scaled_data)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]