What are duplicates?
1) Aduplicate entry means the same record appers more than once in ypur dataset

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [3]:
data={"Id":[101,102,103,102,104],
      "Name":["Rahul","Priya","Amit","Priya","Neha"],
      "Age":[25,28,30,28,26],
      "City":["Delhi","Mumbai","Pune","Mumbai","Delhi"]
}
df=pd.DataFrame(data)
print(df)

    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
3  102  Priya   28  Mumbai
4  104   Neha   26   Delhi

In [6]:
print(df.duplicated()) # a simple command for printing the duplicates 
# if any duplicate is present it shows true either it shows false

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [10]:
duplicates=df[df.duplicated()]
print(duplicates) #  The way to showing only duplicates rows

    Id   Name  Age    City
3  102  Priya   28  Mumbai

In [12]:
df[df.duplicated()] # used to find the occurance of all duplicates

    Id   Name  Age    City
3  102  Priya   28  Mumbai

In [15]:
df[df.duplicated(keep=False)] #  its shows both copies 
# Keep=False "mark Every occurance of a duplicate as tuple"

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [23]:
# checking duplicates based on column 
print(df[df.duplicated("Id",keep=False)])
# this is extremely useful for finding duplicate customer ids employee ids ,product ids
#transaction ids,etc

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [42]:
# checking duplicates using multiple colomns 
print(df[df.duplicated(["Name","Age","Id"],keep=False)])
# we want to check for thr  multiple colomns we need to give the square brakets

    Id   Name  Age    City
1  102  Priya   28  Mumbai
3  102  Priya   28  Mumbai

In [28]:
# count the number of duplicate rows 
print(df.duplicated().sum())

1

In [33]:
# remove duplicates 
print("duplicates removed as per ur requirement")
data=df.drop_duplicates()
print(data)

duplicates removed as per ur requirement
    Id   Name  Age    City
0  101  Rahul   25   Delhi
1  102  Priya   28  Mumbai
2  103   Amit   30    Pune
4  104   Neha   26   Delhi

In [39]:
# removing duplicates based up on columns
print(df.drop_duplicates(subset=["Name"],keep=False))

    Id   Name  Age   City
0  101  Rahul   25  Delhi
2  103   Amit   30   Pune
4  104   Neha   26  Delhi