In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings 
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv(r"D:\Downloads\WA_Fn-UseC_-HR-Employee-Attrition.csv")
df=pd.DataFrame(data)
pd.set_option('display.max_columns', None)
print(df)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
4                    2          1        Medical              1
...                ...        ...            ...            ...
1465                23          2        Medical              1
1466                 6          1        Medical              1
1467                 4          3  Life Sciences              1
1468                 2          3        Medical              1
1469                 8          3        Medical              1

      EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  \
0                  1                        2  Female          94
1                  2                        3    Male          61
2                  4                        4    Male          92
3                  5                        4  Female          56
4                  7                        1    Male          40
...              ...                      ...     ...         ...
1465            2061                        3    Male          41
1466            2062                        4    Male          42
1467            2064                        2    Male          87
1468            2065                        4    Male          63
1469            2068                        2    Male          82

      JobInvolvement  JobLevel                    JobRole  JobSatisfaction  \
0                  3         2            Sales Executive                4
1                  2         2         Research Scientist                2
2                  2         1      Laboratory Technician                3
3                  3         1         Research Scientist                3
4                  3         1      Laboratory Technician                2
...              ...       ...                        ...              ...
1465               4         2      Laboratory Technician                4
1466               2         3  Healthcare Representative                1
1467               4         2     Manufacturing Director                2
1468               2         2            Sales Executive                2
1469               4         2      Laboratory Technician                3

     MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18  \
0           Single           5993        19479                   8      Y
1          Married           5130        24907                   1      Y
2           Single           2090         2396                   6      Y
3          Married           2909        23159                   1      Y
4          Married           3468        16632                   9      Y
...            ...            ...          ...                 ...    ...
1465       Married           2571        12290                   4      Y
1466       Married           9991        21457                   4      Y
1467       Married           6142         5174                   1      Y
1468       Married           5390        13243                   2      Y
1469       Married           4404        10228                   2      Y

     OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
0         Yes                 11                  3                         1
1          No                 23                  4                         4
2         Yes                 15                  3                         2
3         Yes                 11                  3                         3
4          No                 12                  3                         4
...       ...                ...                ...                       ...
1465       No                 17                  3                         3
1466       No                 15                  3                         1
1467      Yes                 20                  4                         2
1468       No                 14                  3                         4
1469       No                 12                  3                         1

      StandardHours  StockOptionLevel  TotalWorkingYears  \
0                80                 0                  8
1                80                 1                 10
2                80                 0                  7
3                80                 0                  8
4                80                 1                  6
...             ...               ...                ...
1465             80                 1                 17
1466             80                 1                  9
1467             80                 1                  6
1468             80                 0                 17
1469             80                 0                  6

      TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                         0                1               6
1                         3                3              10
2                         3                3               0
3                         3                3               8
4                         3                3               2
...                     ...              ...             ...
1465                      3                3               5
1466                      5                3               7
1467                      0                3               6
1468                      3                2               9
1469                      3                4               4

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                      4                        0                     5
1                      7                        1                     7
2                      0                        0                     0
3                      7                        3                     0
4                      2                        2                     2
...                  ...                      ...                   ...
1465                   2                        0                     3
1466                   7                        1                     7
1467                   2                        0                     3
1468                   6                        0                     8
1469                   3                        1                     2

[1470 rows x 35 columns]

## Understanding your Dataset

In [9]:
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5

In [10]:
df.tail(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,2,Male,82,4,2,Laboratory Technician,3,Married,4404,10228,2,Y,No,12,3,1,80,0,6,3,4,4,3,1,2

In [12]:
df.shape

(1470, 35)

In [13]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [15]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,6502.931293,14313.103401,2.693197,15.209524,3.153741,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,4707.956783,7117.786044,2.498009,3.659938,0.360824,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,8047.000000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4919.000000,14235.500000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,8379.000000,20461.500000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [17]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [18]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [20]:
df.index

RangeIndex(start=0, stop=1470, step=1)

In [21]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [36]:
print(df.loc[:,["Age","Attrition"]])
print(df.loc[df["Age"]==45])
print(df.loc[df["Age"]==45,["OverTime",'JobRole']])

      Age Attrition
0      41       Yes
1      49        No
2      37       Yes
3      33        No
4      27        No
...   ...       ...
1465   36        No
1466   39        No
1467   27        No
1468   49        No
1469   34        No

[1470 rows x 2 columns]
      Age Attrition     BusinessTravel  DailyRate              Department  \
67     45        No      Travel_Rarely       1339  Research & Development
77     45        No      Travel_Rarely        193  Research & Development
141    45        No      Travel_Rarely       1316  Research & Development
153    45        No      Travel_Rarely        194  Research & Development
174    45        No      Travel_Rarely       1268                   Sales
194    45        No         Non-Travel       1195  Research & Development
218    45        No         Non-Travel       1052                   Sales
244    45        No      Travel_Rarely        252  Research & Development
249    45        No  Travel_Frequently       1199  Research & Development
268    45        No      Travel_Rarely       1385  Research & Development
311    45        No  Travel_Frequently       1249  Research & Development
334    45        No      Travel_Rarely        549  Research & Development
407    45        No      Travel_Rarely        192  Research & Development
452    45        No      Travel_Rarely        561                   Sales
504    45       Yes  Travel_Frequently        306                   Sales
564    45        No      Travel_Rarely        954                   Sales
603    45        No      Travel_Rarely        252  Research & Development
625    45        No      Travel_Rarely        930                   Sales
696    45        No         Non-Travel        805  Research & Development
713    45        No      Travel_Rarely        974  Research & Development
718    45        No         Non-Travel        248  Research & Development
755    45        No      Travel_Rarely       1234                   Sales
759    45        No      Travel_Rarely        788         Human Resources
805    45        No         Non-Travel       1050                   Sales
854    45        No      Travel_Rarely       1457  Research & Development
913    45       Yes      Travel_Rarely       1449                   Sales
936    45        No  Travel_Frequently        364  Research & Development
1034   45        No      Travel_Rarely       1038  Research & Development
1037   45        No      Travel_Rarely       1448  Research & Development
1092   45        No      Travel_Rarely        950  Research & Development
1099   45        No      Travel_Rarely        538  Research & Development
1142   45        No      Travel_Rarely       1015  Research & Development
1143   45        No         Non-Travel        336                   Sales
1160   45        No      Travel_Rarely       1329  Research & Development
1221   45        No         Non-Travel       1238  Research & Development
1225   45        No      Travel_Rarely       1005  Research & Development
1243   45        No      Travel_Rarely        176         Human Resources
1314   45        No         Non-Travel        589                   Sales
1346   45        No      Travel_Rarely        556  Research & Development
1362   45        No  Travel_Frequently       1297  Research & Development
1454   45        No      Travel_Rarely        374                   Sales

      DistanceFromHome  Education    EducationField  EmployeeCount  \
67                   7          3     Life Sciences              1
77                   6          4             Other              1
141                 29          3           Medical              1
153                  9          3     Life Sciences              1
174                  4          2     Life Sciences              1
194                  2          2           Medical              1
218                  6          3           Medical              1
244                  1          3             Other              1
249                  7          4     Life Sciences              1
268                 20          2           Medical              1
311                  7          3     Life Sciences              1
334                  8          4             Other              1
407                 10          2     Life Sciences              1
452                  2          3             Other              1
504                 26          4     Life Sciences              1
564                  2          2  Technical Degree              1
603                  2          3     Life Sciences              1
625                  9          3         Marketing              1
696                  4          2     Life Sciences              1
713                  1          4           Medical              1
718                 23          2     Life Sciences              1
755                 11          2     Life Sciences              1
759                 24          4           Medical              1
805                  9          4     Life Sciences              1
854                  7          3           Medical              1
913                  2          3         Marketing              1
936                 25          3           Medical              1
1034                20          3           Medical              1
1037                29          3  Technical Degree              1
1092                28          3  Technical Degree              1
1099                 1          4  Technical Degree              1
1142                 5          5           Medical              1
1143                26          3         Marketing              1
1160                 2          2             Other              1
1221                 1          1     Life Sciences              1
1225                28          2  Technical Degree              1
1243                 4          3     Life Sciences              1
1314                 2          4     Life Sciences              1
1346                25          2     Life Sciences              1
1362                 1          4           Medical              1
1454                20          3     Life Sciences              1

      EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  \
67                86                        2    Male          59
77               101                        4    Male          52
141              192                        3    Male          83
153              206                        2    Male          60
174              240                        3  Female          30
194              264                        1    Male          65
218              302                        4  Female          57
244              336                        3    Male          70
249              341                        1    Male          77
268              372                        3    Male          79
311              425                        1    Male          97
334              452                        4    Male          75
407              544                        1    Male          69
452              606                        4    Male          61
504              684                        1  Female         100
564              783                        2    Male          46
603              834                        2  Female          95
625              864                        4    Male          74
696              972                        3    Male          57
713              996                        4  Female          91
718             1002                        4    Male          42
755             1045                        4  Female          90
759             1049                        2    Male          36
805             1117                        2  Female          65
854             1195                        1  Female          83
913             1277                        1  Female          94
936             1306                        2  Female          83
1034            1460                        2    Male          95
1037            1465                        2    Male          55
1092            1546                        4    Male          97
1099            1553                        1    Male          66
1142            1611                        3  Female          50
1143            1612                        1    Male          52
1160            1635                        4  Female          59
1221            1712                        3    Male          74
1225            1719                        4  Female          48
1243            1744                        3  Female          56
1314            1845                        3  Female          67
1346            1888                        2  Female          93
1362            1922                        2    Male          44
1454            2046                        4  Female          50

      JobInvolvement  JobLevel                    JobRole  JobSatisfaction  \
67                 3         3         Research Scientist                1
77                 3         3          Research Director                1
141                3         1         Research Scientist                4
153                3         2      Laboratory Technician                2
174                3         2            Sales Executive                1
194                2         4                    Manager                4
218                2         3            Sales Executive                4
244                4         5                    Manager                4
249                4         2     Manufacturing Director                3
268                3         4  Healthcare Representative                4
311                3         3      Laboratory Technician                1
334                3         2         Research Scientist                4
407                3         1         Research Scientist                4
452                3         2            Sales Executive                2
504                3         2            Sales Executive                1
564                1         2       Sales Representative                3
603                2         1         Research Scientist                3
625                3         3            Sales Executive                1
696                3         2      Laboratory Technician                2
713                3         1      Laboratory Technician                4
718                3         2      Laboratory Technician                1
755                3         4                    Manager                4
759                3         1            Human Resources                2
805                2         2            Sales Executive                3
854                3         1         Research Scientist                3
913                1         5                    Manager                2
936                3         5                    Manager                2
1034               1         3  Healthcare Representative                1
1037               3         3     Manufacturing Director                4
1092               3         1         Research Scientist                4
1099               3         3  Healthcare Representative                2
1142               1         2      Laboratory Technician                1
1143               2         2            Sales Executive                1
1160               2         2     Manufacturing Director                4
1221               2         3  Healthcare Representative                3
1225               2         4          Research Director                2
1243               1         3            Human Resources                3
1314               3         2            Sales Executive                3
1346               2         2     Manufacturing Director                4
1362               3         2  Healthcare Representative                3
1454               3         2            Sales Executive                3

     MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18  \
67        Divorced           9724        18787                   2      Y
77         Married          13245        15067                   4      Y
141         Single           3452         9752                   5      Y
153       Divorced           2348        10901                   8      Y
174       Divorced           5006         6319                   4      Y
194        Married          16792        20462                   9      Y
218         Single           8865        16840                   6      Y
244        Married          19202        15970                   0      Y
249        Married           6434         5118                   4      Y
268        Married          13496         7501                   0      Y
311       Divorced           5210        20308                   1      Y
334        Married           3697         9278                   9      Y
407        Married           2654         9655                   3      Y
452        Married           4805        16177                   0      Y
504        Married           4286         5630                   2      Y
564         Single           6632        12388                   0      Y
603         Single           2274         6153                   1      Y
625       Divorced          10761        19239                   4      Y
696        Married           4447        23163                   1      Y
713       Divorced           2270        11005                   3      Y
718        Married           3633        14039                   1      Y
755        Married          17650         5404                   3      Y
759         Single           2177         8318                   1      Y
805        Married           5593        17970                   1      Y
854        Married           4477        20100                   4      Y
913         Single          18824         2493                   2      Y
936         Single          18061        13035                   3      Y
1034      Divorced          10851        19863                   2      Y
1037       Married           9380        14720                   4      Y
1092       Married           2132         4585                   4      Y
1099      Divorced           7441        20933                   1      Y
1142        Single           5769        23447                   1      Y
1143       Married           4385        24162                   1      Y
1160      Divorced           5770         5388                   1      Y
1221       Married          10748         3395                   3      Y
1225        Single          16704        17119                   1      Y
1243       Married           9756         6595                   4      Y
1314       Married           5154        19665                   4      Y
1346       Married           5906        23888                   0      Y
1362        Single           5399        14511                   4      Y
1454        Single           4850        23333                   8      Y

     OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
67         No                 17                  3                         3
77        Yes                 14                  3                         2
141        No                 13                  3                         2
153        No                 18                  3                         3
174       Yes                 11                  3                         1
194        No                 23                  4                         4
218        No                 12                  3                         4
244        No                 11                  3                         3
249        No                 17                  3                         4
268       Yes                 14                  3                         2
311        No                 18                  3                         1
334        No                 14                  3                         1
407        No                 21                  4                         4
452        No                 19                  3                         2
504        No                 14                  3                         4
564        No                 13                  3                         1
603        No                 14                  3                         4
625       Yes                 12                  3                         3
696        No                 12                  3                         2
713        No                 14                  3                         4
718       Yes                 15                  3                         3
755        No                 13                  3                         2
759        No                 16                  3                         1
805        No                 13                  3                         4
854       Yes                 19                  3                         3
913       Yes                 16                  3                         1
936        No                 22                  4                         3
1034      Yes                 18                  3                         2
1037      Yes                 18                  3                         4
1092       No                 20                  4                         4
1099       No                 12                  3                         1
1142      Yes                 14                  3                         1
1143       No                 15                  3                         1
1160       No                 19                  3                         1
1221       No                 23                  4                         4
1225       No                 11                  3                         3
1243       No                 21                  4                         3
1314       No                 22                  4                         2
1346       No                 13                  3                         4
1362       No                 12                  3                         3
1454       No                 15                  3                         3

      StandardHours  StockOptionLevel  TotalWorkingYears  \
67               80                 1                 25
77               80                 0                 17
141              80                 0                  9
153              80                 1                 20
174              80                 1                  9
194              80                 1                 22
218              80                 0                 23
244              80                 1                 25
249              80                 1                  9
268              80                 0                 21
311              80                 1                 24
334              80                 2                 12
407              80                 2                  8
452              80                 1                  9
504              80                 2                  5
564              80                 0                  9
603              80                 0                  1
625              80                 1                 18
696              80                 0                  9
713              80                 2                  8
718              80                 1                  9
755              80                 1                 26
759              80                 0                  6
805              80                 1                 15

In [37]:
df.iloc[0,1]

'Yes'

In [38]:
print(df.iloc[0:10,0:2])

   Age Attrition
0   41       Yes
1   49        No
2   37       Yes
3   33        No
4   27        No
5   32        No
6   59        No
7   30        No
8   38        No
9   36        No

## Filtering the Data 
1. Boolean filtering
       ↓
2. AND / OR / NOT
       ↓
3. isin()
       ↓
4. between()
       ↓
5. isna() / notna()
       ↓
6. loc[]
       ↓
7. String filtering
       ↓
8. Date filtering
       ↓
9. query()
       ↓
10. Combining filtering + groupby + aggregation

In [39]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [66]:
df[(df.loc[:,"Age"]==45)&(df["Attrition"]=="Yes")]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
504,45,Yes,Travel_Frequently,306,Sales,26,4,Life Sciences,1,684,1,Female,100,3,2,Sales Executive,1,Married,4286,5630,2,Y,No,14,3,4,80,2,5,4,3,1,1,0,0
913,45,Yes,Travel_Rarely,1449,Sales,2,3,Marketing,1,1277,1,Female,94,1,5,Manager,2,Single,18824,2493,2,Y,Yes,16,3,1,80,0,26,2,3,24,10,1,11

In [70]:
print(df[(df["Age"]<100)&(df["BusinessTravel"]=="Non_Travel")])

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

In [72]:
df.query("Age==45").head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
67,45,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,Research Scientist,1,Divorced,9724,18787,2,Y,No,17,3,3,80,1,25,2,3,1,0,0,0
77,45,No,Travel_Rarely,193,Research & Development,6,4,Other,1,101,4,Male,52,3,3,Research Director,1,Married,13245,15067,4,Y,Yes,14,3,2,80,0,17,3,4,0,0,0,0
141,45,No,Travel_Rarely,1316,Research & Development,29,3,Medical,1,192,3,Male,83,3,1,Research Scientist,4,Single,3452,9752,5,Y,No,13,3,2,80,0,9,2,2,6,5,0,3
153,45,No,Travel_Rarely,194,Research & Development,9,3,Life Sciences,1,206,2,Male,60,3,2,Laboratory Technician,2,Divorced,2348,10901,8,Y,No,18,3,3,80,1,20,2,1,17,9,0,15
174,45,No,Travel_Rarely,1268,Sales,4,2,Life Sciences,1,240,3,Female,30,3,2,Sales Executive,1,Divorced,5006,6319,4,Y,Yes,11,3,1,80,1,9,3,4,5,4,0,3

In [76]:
df.iloc[65:68,0].isin([45]).head(5)

65    False
66    False
67     True
Name: Age, dtype: bool

In [79]:
df[df["Age"].between(45,46)].head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,2,Female,83,3,5,Manager,1,Single,18947,22822,3,Y,No,12,3,4,80,0,22,2,2,2,2,2,1
48,46,No,Travel_Frequently,1211,Sales,5,4,Marketing,1,62,1,Male,98,3,2,Sales Executive,4,Single,5772,20445,4,Y,Yes,21,4,3,80,0,14,4,3,9,6,0,8
67,45,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,Research Scientist,1,Divorced,9724,18787,2,Y,No,17,3,3,80,1,25,2,3,1,0,0,0
77,45,No,Travel_Rarely,193,Research & Development,6,4,Other,1,101,4,Male,52,3,3,Research Director,1,Married,13245,15067,4,Y,Yes,14,3,2,80,0,17,3,4,0,0,0,0
79,46,No,Travel_Rarely,945,Human Resources,5,2,Medical,1,103,2,Male,80,3,2,Human Resources,2,Divorced,5021,10425,8,Y,Yes,22,4,4,80,1,16,2,3,4,2,0,2

## Checking the Missing values

In [103]:
print(df.isna().sum().head(5))
print(df.isnull().sum().head(5))
print(df[["Age","Attrition","BusinessTravel"]].notna().head())
print(df.notnull().sum())

Age               0
Attrition         0
BusinessTravel    0
DailyRate         0
Department        0
dtype: int64
Age               0
Attrition         0
BusinessTravel    0
DailyRate         0
Department        0
dtype: int64
    Age  Attrition  BusinessTravel
0  True       True            True
1  True       True            True
2  True       True            True
3  True       True            True
4  True       True            True
Age                         1470
Attrition                   1470
BusinessTravel              1470
DailyRate                   1470
Department                  1470
DistanceFromHome            1470
Education                   1470
EducationField              1470
EmployeeCount               1470
EmployeeNumber              1470
EnvironmentSatisfaction     1470
Gender                      1470
HourlyRate                  1470
JobInvolvement              1470
JobLevel                    1470
JobRole                     1470
JobSatisfaction             1470
MaritalStatus               1470
MonthlyIncome               1470
MonthlyRate                 1470
NumCompaniesWorked          1470
Over18                      1470
OverTime                    1470
PercentSalaryHike           1470
PerformanceRating           1470
RelationshipSatisfaction    1470
StandardHours               1470
StockOptionLevel            1470
TotalWorkingYears           1470
TrainingTimesLastYear       1470
WorkLifeBalance             1470
YearsAtCompany              1470
YearsInCurrentRole          1470
YearsSinceLastPromotion     1470
YearsWithCurrManager        1470
dtype: int64

In [102]:
df["Age"].duplicated().head(5)
print(df.loc[:,"Age"].duplicated().head(100))
print(df["Age"].drop_duplicates())

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96     True
97     True
98    False
99     True
Name: Age, Length: 100, dtype: bool
0      41
1      49
2      37
3      33
4      27
5      32
6      59
7      30
8      38
9      36
10     35
11     29
12     31
13     34
14     28
17     22
18     53
20     24
23     21
27     42
28     44
29     46
33     39
35     43
36     50
42     26
50     48
65     55
67     45
85     56
86     23
87     51
90     40
95     54
98     58
102    20
107    25
127    19
163    57
190    52
271    47
296    18
411    60
Name: Age, dtype: int64

## Grouping and Aggregation

In [104]:
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [112]:
df.groupby("BusinessTravel")["Age"].mean()
print(df.groupby("BusinessTravel")["Age"].agg(["mean","median","std"]))

                        mean  median       std
BusinessTravel
Non-Travel         36.620000    36.0  8.776624
Travel_Frequently  36.454874    35.0  8.547541
Travel_Rarely      37.092042    36.0  9.337414

In [108]:
df["Age"].apply(lambda x:x*1.10)

0       45.1
1       53.9
2       40.7
3       36.3
4       29.7
        ...
1465    39.6
1466    42.9
1467    29.7
1468    53.9
1469    37.4
Name: Age, Length: 1470, dtype: float64